cri_api/urls.py
from django.urls import include, path

from rest_framework import routers

from . import views

router = routers.DefaultRouter()
router.register("campus", views.CampusViewSet)
router.register("groups", views.CRIGroupViewSet)
router.register("users", views.CRIUserViewSet)

urlpatterns = [
    path(
        "groups/<slug:slug>/members/",
        views.CRIGroupMembersView.as_view(),
        name="crigroup-members",
    ),
    path(
        "groups/<slug:slug>/history/",
        views.CRIGroupHistoryView.as_view(),
        name="crigroup-history",
    ),
    path("cards/", views.CRICardsView.as_view(), name="cricards-create"),
    path("", include(router.urls)),
]

cri_frontend/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import RedirectView

from cri_frontend import views

urlpatterns = [
    # This path is kept to avoid breaking bookmarks on the old intranet
    path(
        "accounts/profile/",
        RedirectView.as_view(url=reverse_lazy("criuser_self"), permanent=True),
    ),
    path("", views.IndexView.as_view(), name="index"),
    path("maps/", views.NotAvailableView.as_view(), name="maps"),
    path("search/", views.SearchFormView.as_view(), name="search"),
    path("me/", views.CRIUserSelfView.as_view(), name="criuser_self"),
    path("users/", views.UserlistAction.as_view(), name="userlist_action"),
    path(
        "users/<str:username>/",
        views.CRIUserView.as_view(),
        name="criuser_detail",
    ),
    path(
        "users/<str:username>/notes/",
        views.CRIUserNotesView.as_view(),
        name="criusernote_list",
    ),
    path(
        "users/<str:username>/notes/create/",
        views.CRIUserNoteCreateView.as_view(),
        name="criusernote_create",
    ),
    path(
        "users/<str:username>/notes/<int:pk>/edit",
        views.CRIUserNoteUpdateView.as_view(),
        name="criusernote_update",
    ),
    path(
        "users/<str:username>/notes/<int:pk>/delete",
        views.CRIUserNoteDeleteView.as_view(),
        name="criusernote_delete",
    ),
    path(
        "users/<str:username>/password/",
        views.CRIUserChangePasswordView.as_view(),
        name="criuser_password",
    ),
    path(
        "users/<str:username>/oidc/",
        views.CRIUserOIDCView.as_view(),
        name="criuser_oidc",
    ),
    path(
        "oidc/consent/<int:pk>/delete",
        views.OIDCConsentDeleteView.as_view(),
        name="criuser_oidc_delete_consent",
    ),
    path(
        "users/<str:username>/ssh-keys/",
        views.CRIUserSSHKeysView.as_view(),
        name="criuser_ssh_keys",
    ),
    path(
        "ssh-keys/<int:pk>/delete",
        views.SSHKeyDeleteView.as_view(),
        name="criuser_ssh_keys_delete",
    ),
    path(
        "users/<str:username>/logs/",
        views.CRIUserConnectionLogView.as_view(),
        name="criuser_logs",
    ),
    path(
        "users/<str:username>/tasks/",
        views.CRIUserTasksView.as_view(),
        name="criuser_tasks",
    ),
    path(
        "group/<slug:slug>/",
        views.CRIGroupView.as_view(),
        name="crigroup_detail",
    ),
    path(
        "password/change/done/",
        views.IndexView.as_view(),
        name="password_change_done",
    ),
    path(
        "<str:username>.keys",
        views.CRIUserSSHKeysShortcutView.as_view(),
        name="criuser_ssh_keys_shortcut",
    ),
]

cri_intranet/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path, re_path

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="CRI API",
        default_version="v2.0-alpha",
        # description="Test description",
        contact=openapi.Contact(email="tickets@cri.epita.fr"),
        # license=openapi.License(name="BSD License"),
    ),
    validators=["ssv"],
    public=False,
    permission_classes=(permissions.AllowAny,),
    patterns=[path("api/v2/", include("cri_api.urls"))],
)

urlpatterns = [
    path("auth/", include("cri_auth.urls")),
    path("admin/", admin.site.urls),
    path("api/v2/", include("cri_api.urls")),
    path("api-auth/", include("rest_framework.urls")),
    re_path(
        r"swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
    path("cards/", include("cri_cards.urls")),
    path("", include("cri_frontend.urls")),
    path("", include("cri_legacy.urls")),
    path("", include("oidc_provider.urls", namespace="oidc_provider")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

cri_auth/models.py
import itertools

from django.db import models
from django.dispatch import receiver
from django.contrib.auth import (
    get_user_model,
    signals as auth_signals,
    BACKEND_SESSION_KEY,
)
from django.utils import timezone
from django.conf import settings

from oidc_provider.models import Client as OIDCClient

from cri_models import ldap, sync
from cri_models.models import CRIGroup

import uuid


class AuthGroup(models.Model):
    groups_clients_mapping = models.ForeignKey(
        "AuthGroupsClientsMapping", on_delete=models.CASCADE
    )

    group = models.ForeignKey(CRIGroup, on_delete=models.CASCADE)

    clients_can_see_private_subgroups = models.BooleanField(default=False)

    group_managers_can_manage_clients = models.BooleanField(default=False)

    group_is_allowed = models.BooleanField(default=True)

    _roles = models.CharField(max_length=150, blank=True, verbose_name="roles")

    class Meta:
        pass

    @property
    def roles(self):
        return self._roles.split()

    @roles.setter
    def roles(self, roles):
        self._roles = " ".join(roles)


class AuthGroupsClientsMapping(models.Model):
    name = models.CharField(max_length=100)

    managers = models.ManyToManyField(get_user_model(), blank=True)

    groups = models.ManyToManyField(CRIGroup, through=AuthGroup, blank=True)

    is_restricted = models.BooleanField(
        default=False,
        help_text=(
            "If enabled, only managers and explicitly allowed groups will be "
            "allowed to sign in with the clients"
        ),
    )

    class Meta:
        verbose_name = "Groups-Clients mapping"

    def __str__(self):
        return self.name

    def get_managers(self):
        managers = set(self.managers.all())
        for authgroup in self.authgroup_set.filter(
            group_managers_can_manage_clients=True
        ):
            managers |= set(authgroup.group.get_managers())
        return managers

    def get_users(self):
        users = set()
        for authgroup in self.authgroup_set.filter(group_is_allowed=True):
            users |= set(authgroup.group.get_members())
        return users

    def get_users_by_roles(self):
        roles = {}
        for authgroup in self.authgroup_set.all():
            users = set(authgroup.group.get_members())
            for role in authgroup.roles:
                roles.setdefault(role, set()).update(users)
        return roles

    def get_user_roles(self, user):
        ag_list = AuthGroup.objects.filter(
            groups_clients_mapping=self, group__in=user.get_groups()
        ).distinct()
        return set(itertools.chain.from_iterable([ag.roles for ag in ag_list]))

    def get_user_groups(self, user):
        prefix = "computed_parents__authgroup"
        return (
            user.get_groups()
            .filter(
                models.Q(private=False)
                | models.Q(authgroup__groups_clients_mapping=self)
                | models.Q(
                    **{
                        f"{prefix}__groups_clients_mapping": self,
                        f"{prefix}__clients_can_see_private_subgroups": True,
                    }
                )
            )
            .distinct()
        )

    def is_user_allowed(self, user):
        if not self.is_restricted:
            return True
        prefix = "memberships__group__authgroup"
        return (
            get_user_model()
            .objects.filter(
                models.Q(authgroupsclientsmapping=self)
                | models.Q(
                    models.Q(
                        models.Q(memberships__begin_at__lte=timezone.now())
                        | models.Q(memberships__begin_at__isnull=True),
                        models.Q(memberships__end_at__gte=timezone.now())
                        | models.Q(memberships__end_at__isnull=True),
                    ),
                    **{
                        f"{prefix}__groups_clients_mapping": self,
                        f"{prefix}__group_is_allowed": True,
                    },
                )
                | models.Q(
                    managed_groups__authgroupsclientsmapping=self,
                )
                | models.Q(
                    managed_groups__computed_children__authgroupsclientsmapping=self,
                ),
                pk=user.pk,
            )
            .exists()
        )

    @classmethod
    def get_mappings_managed_by_user(cls, user):
        if user.has_perm("cri_auth.edit_authgroupsclientsmapping"):
            return cls.objects.all()
        prefix = "authgroup"
        return cls.objects.filter(
            models.Q(managers=user)
            | models.Q(
                **{
                    f"{prefix}__group_managers_can_manage_clients": True,
                    f"{prefix}__group__managers": user,
                }
            )
            | models.Q(
                **{
                    f"{prefix}__group_managers_can_manage_clients": True,
                    f"{prefix}__group__computed_parents__managers": user,
                }
            )
        ).distinct()


class CRIServiceLDAPSyncAdapter(sync.SyncedLDAPModelAdapter):
    sync_remote_model = ldap.LDAPGroup.scoped(f"ou=services,{settings.LDAP_BASE_DN}")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._roles = self.obj.get_users_by_roles()

    def ldap_dn_from_obj(self, role=None):
        if self.obj.slug:
            if not role:
                return self.sync_remote_model(name=self.obj.slug).build_dn()
            model = self.sync_remote_model.scoped(self.ldap_dn_from_obj())
            return model(name=f"{role}_{self.obj.slug}").build_dn()
        return None

    def get_sync_local_obj_id_multi(self):
        return [m[0] for m in self.get_sync_remote_obj_id_multi(None)]

    def get_sync_remote_obj_id_multi(self, _remote_objects):
        dn = self.ldap_dn_from_obj(role=None)
        yield ((self.obj.pk, None), dn)
        for role in self._roles:
            dn = self.ldap_dn_from_obj(role=role)
            yield ((self.obj.pk, role), dn)

    def get_sync_local_data_multi(self):
        dn = self.ldap_dn_from_obj(self.obj)
        managers = set(u.ldap_dn for u in self.obj.get_managers() if u.ldap_dn)

        yield (
            (self.obj.pk, None),
            {
                "managers": managers,
                "members": set(u.ldap_dn for u in self.obj.get_users() if u.ldap_dn),
                "name": self.obj.slug,
            },
        )

        for role, members in self.obj.get_users_by_roles().items():
            name = f"{role}_{self.obj.slug}"
            yield (
                (self.obj.pk, role),
                {
                    "dn": dn,
                    "managers": managers,
                    "members": set(u.ldap_dn for u in members if u.ldap_dn),
                    "name": name,
                    "description": role,
                },
            )

    @staticmethod
    def get_sync_remote_data(remote_obj):
        SYNC_FIELDS = ("name",)
        data = {
            "managers": set(remote_obj.managers),
            "members": set(remote_obj.members),
            "description": remote_obj.description,
            **{f: getattr(remote_obj, f) for f in SYNC_FIELDS},
        }
        return (remote_obj.dn, data)


class AuthMethodMixin(sync.SyncedModelMixin, models.Model):
    groups_clients_mapping = models.ForeignKey(
        AuthGroupsClientsMapping, on_delete=models.PROTECT
    )

    slug = models.SlugField(unique=True, blank=True, default=uuid.uuid4)

    class Meta:
        abstract = True

    class SyncMeta:
        sync_adapters = (CRIServiceLDAPSyncAdapter,)

    def get_users(self):
        return self.groups_clients_mapping.get_users()

    def get_managers(self):
        return self.groups_clients_mapping.get_managers()

    def get_users_by_roles(self):
        return self.groups_clients_mapping.get_users_by_roles()

    def get_user_roles(self, user):
        return self.groups_clients_mapping.get_user_roles(user)

    def get_user_groups(self, user):
        return self.groups_clients_mapping.get_user_groups(user)

    def is_user_allowed(self, user):
        return self.groups_clients_mapping.is_user_allowed(user)


class OIDCClientExtension(AuthMethodMixin):
    client = models.OneToOneField(OIDCClient, on_delete=models.CASCADE)

    is_legacy = models.BooleanField(
        default=False,
        help_text=(
            "If enabled, the claims returned by the epita scope will match the old "
            "OIDC API. Do not use for new OIDC clients."
        ),
    )

    class Meta:
        verbose_name = "OIDC client extension"

    def __str__(self):
        return self.client.name

    @classmethod
    def get_clients_managed_by_user(cls, user):
        if user.has_perm("oidc_provider.view_client"):
            return OIDCClient.objects.all()
        agcm_managed_by_user = AuthGroupsClientsMapping.get_mappings_managed_by_user(
            user
        )
        return OIDCClient.objects.filter(
            models.Q(owner=user)
            | models.Q(
                oidcclientextension__groups_clients_mapping__in=agcm_managed_by_user
            )
        ).distinct()

    @classmethod
    def from_client(cls, client):
        related_name = cls._meta.get_field("client").remote_field.get_accessor_name()
        if not hasattr(client, related_name):
            return cls.objects.create(
                client=client,
                AuthGroupsClientsMapping=AuthGroupsClientsMapping.objects.create(),
            )
        return getattr(client, related_name)


class ConnectionLogEntry(models.Model):
    KIND_CHOICES = (
        ("password", "Sign-in with password"),
        ("kerberos_spnego", "Sign-in with Kerberos (SPNEGO)"),
        ("ldap_password", "Sign-in with LDAP (password)"),
        ("office365_oauth2", "Sign-in with Office365 SSO"),

cri_frontend/models.py
from django.db import models


class Shortcut(models.Model):
    title = models.CharField(max_length=100)

    description = models.TextField(blank=True)

    url = models.URLField()

    class Meta:
        ordering = ("title",)

    def __str__(self):
        return self.title

cri_frontend/templates/cri_frontend/_criuser_nav.html
<form id="impersonate_form" method="POST" action="{% url 'impersonate' criuser.username %}">
    {% csrf_token %}
</form>
<form id="card_form" class="form" method="POST" action="{% url 'cards_issue' %}">
    {% csrf_token %}
    <input type="hidden" name="user_list" value="{{ criuser.pk }}" />
</form>
<div class="list-group flex-column" aria-orientation="vertical">
    <a class="list-group-item list-group-item-action{% if current_page == "account-info" %} active{% else %} text-primary{% endif %}" href="{% url 'criuser_detail' criuser.username %}" role="tab">
        <i class="fas fa-address-card"></i>
        Account information
    </a>
    {% if note_list or writable_scopes %}
    <a class="list-group-item list-group-item-action{% if current_page == "user-notes" %} active{% else %} text-primary{% endif %} d-flex justify-content-between align-items-center" href="{% url 'criusernote_list' criuser.username %}" role="tab">
        <span>
            <i class="far fa-comment-alt"></i>
            Notes
            <span class="badge badge-secondary">
                {{ note_list|length }}
            </span>
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </a>
    {% endif %}
    {% if criuser == user or perms.cri_models.update_criuser_passwords or user in criuser.criserviceaccount.get_managers %}
    <a class="list-group-item list-group-item-action{% if current_page == "change-password" %} active{% else %} text-primary{% endif %} d-flex justify-content-between align-items-center" href="{% url 'criuser_password' criuser.username %}" role="tab">
        <span>
            <i class="fas fa-lock"></i>
            Change password
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </a>
    {% endif %}
    {% if criuser == user or perms.cri_models.manage_criuser_oidc %}
    <a class="list-group-item list-group-item-action{% if current_page == "oidc" %} active{% else %} text-primary{% endif %} d-flex justify-content-between align-items-center" href="{% url 'criuser_oidc' criuser.username %}" role="tab">
        <span>
            <i class="fab fa-openid"></i>
            OpenID Connect
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </a>
    {% endif %}
    {% with count=criuser.sshpublickey_set.count %}
    <a class="list-group-item list-group-item-action{% if current_page == "ssh-keys" %} active{% else %}{% if not count %} text-danger{% else %} text-primary{% endif %}{% endif %}" href="{% url 'criuser_ssh_keys' criuser.username %}" role="tab">
        <i class="fas fa-key"></i>
        SSH keys
        <span class="badge badge-{% if count %}success{%else%}danger{% endif %}">
            {{ count }}
        </span>
    </a>
    {% endwith %}
    {% if criuser == user or perms.cri_auth.view_connectionlogentry %}
    <a class="list-group-item list-group-item-action{% if current_page == "logs" %} active{% else %} text-primary{% endif %} d-flex justify-content-between align-items-center" href="{% url 'criuser_logs' criuser.username %}" role="tab">
        <span>
            <i class="fas fa-list"></i>
            Connection logs
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </a>
    {% endif %}
    {% if criuser == user or perms.cri_tasks.view_task %}
    <a class="list-group-item list-group-item-action{% if current_page == "tasks" %} active{% else %} text-primary{% endif %} d-flex justify-content-between align-items-center" href="{% url 'criuser_tasks' criuser.username %}" role="tab">
        <span>
            <i class="fas fa-tasks"></i>
            Tasks
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </a>
    {% endif %}
    {% if perms.cri_cards.issue_card and not criuser.criserviceaccount %}
    <button form="card_form" type="submit" class="list-group-item list-group-item-action{% if current_page == "issue_card" %} active{% else %} text-primary{% endif %} text-info d-flex justify-content-between align-items-center">
        <span>
            <i class="fas fa-id-card"></i>
            Issue an access card
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This link is not visible for everyone">
            <i class="fas fa-eye-slash"></i>
        </span>
    </button>
    {% endif %}
    {% if criuser != user and perms.cri_models.impersonate and not criuser.is_superuser %}
    <button form="impersonate_form" type="submit" class="list-group-item list-group-item-action text-warning d-flex justify-content-between align-items-center" href="{% url 'impersonate' criuser.username %}" role="tab">
        <span>
            <i class="fas fa-user-secret"></i>
            Impersonate
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This action is only shown to admins">
            <i class="fas fa-eye-slash"></i>
            <i class="fas fa-wrench"></i>
        </span>
    </button>
    {% endif %}
    {% if user.is_staff and perms.cri_models.view_criuser %}
    {% if criuser.criserviceaccount %}
    <a class="list-group-item list-group-item-action text-warning d-flex justify-content-between align-items-center" href="{% url 'admin:cri_models_criserviceaccount_change' criuser.criserviceaccount.pk %}" role="tab">
    {% else %}
    <a class="list-group-item list-group-item-action text-warning d-flex justify-content-between align-items-center" href="{% url 'admin:cri_models_criuser_change' criuser.pk %}" role="tab">
    {% endif %}
        <span>
            <i class="fas fa-wrench"></i>
            View on admin site
        </span>
        <span data-toggle="tooltip" data-placement="right" title="This action is only shown to admins">
            <i class="fas fa-eye-slash"></i>
            <i class="fas fa-wrench"></i>
        </span>
    </a>
    {% endif %}
</div>

cri_frontend/templates/cri_frontend/_criuser_note.html
{% load humanize %}
<div class="card mb-2 {% if note.secret %}border-danger{% endif %}">
    <div class="card-body media">
        <div class="text-center mr-3">
            <div>
                <a href="{% url 'criuser_detail' username=note.author.username %}" title="{{ note.author.get_full_name }}">
                    <img src="{{ note.author.picture_square }}" style="max-width: 100px;" class="img-thumbnail" alt="{{ note.author }}" />
                </a>
            </div>
            {% if note.author == user or note.scope in writable_scopes %}
            <div class="mt-2">
                <a class="btn btn-sm btn-primary" href="{% url 'criusernote_update' username=criuser pk=note.pk %}" role="button" data-toggle="tooltip" data-placement="bottom" title="edit">
                    <i class="fas fa-edit"></i>
                </a>
                <a class="btn btn-sm btn-danger" href="{% url 'criusernote_delete' username=criuser pk=note.pk %}" role="button" data-toggle="tooltip" data-placement="bottom" title="delete">
                    <i class="fas fa-trash"></i>
                </a>
                {% if user.is_staff and perms.cri_models.criusernote_view %}
                <a class="btn btn-sm btn-outline-warning" href="{% url 'admin:cri_models_criusernote_change' note.pk %}" role="button" data-toggle="tooltip" data-placement="bottom" title="view on admin site">
                    <i class="fas fa-wrench"></i>
                </a>
                {% endif %}
            </div>
            {% endif %}
        </div>
        <div class="media-body">
            {% if note.event_title or note.event_kind or note.event_date or note.external_ref %}
            <h5 class="mt-0">
                {% if note.external_ref %}
                <a class="btn btn-sm btn-outline-info" href="{{ note.get_external_ref_url }}" target="_blank">
                    {{ note.get_external_ref }}
                </a>
                {% endif %}
                {% if note.event_kind %}
                <span class="badge badge-primary">
                    {{ note.event_kind }}
                </span>
                {% endif %}

                {{ note.event_title }}

                {% if note.event_date %}
                {{ note.event_date }}
                {% endif %}
            </h5>
            {% endif %}
            {{ note.content|safe }}
        </div>
    </div>
    <div class="card-footer d-flex justify-content-between">
        <div>
            {% if note.secret %}
            <span class="text-danger mr-3" data-toggle="tooltip" data-placement="right" title="This note is not shown to the user">
                <i class="fas fa-eye-slash"></i>
            </span>
            {% endif %}
            <strong>Created:</strong>
            <span data-toggle="tooltip" data-placement="top" title="{{ note.created_at }}">{{ note.created_at|naturaltime }}</span>

            {% if note.updated_at %}
            <strong class="ml-3">Updated:</strong>
            <span data-toggle="tooltip" data-placement="top" title="{{ note.updated_at }}">{{ note.updated_at|naturaltime }}</span>
            {% if note.updated_by %}
            (<a href="{{ note.updated_by.get_absolute_url }}"><i class="fas fa-user"></i> {{ note.updated_by.username }}</a>)
            {% else %}
            (<em><i class="fas fa-user"></i> unknown</em>)
            {% endif %}
            {% endif %}
        </div>
        <div>
            {% for label in note.labels.all %}
            <span class="badge badge-secondary">
                {{ label }}
            </span>
            {% endfor %}
        </div>
    </div>
</div>

cri_frontend/templates/cri_frontend/_extra_link.html
{% load humanize %}
{% if extra_link.type == "date" or extra_link.type == "text" %}
<span class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
    {% if extra_link.title or extra_link.icon %}
    <strong>
        {% if extra_link.icon %}
        <i class="{{ extra_link.icon }}"></i>
        {% endif %}
        {{ extra_link.title }}
    </strong>
    {% endif %}
    {% if extra_link.type == "date" %}
    {% if extra_link.content %}
    <span data-toggle="tooltip" data-placement="left" title="{{ extra_link.content }}">{{ extra_link.content|naturaltime }}</span>
    {% else %}
    <em class="text-secondary">never</em>
    {% endif %}
    {% else %}
    <span>{{ extra_link.content }}</span>
    {% endif %}
</span>
{% elif extra_link.type == "link" %}
<a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-primary" href="{{ extra_link.content }}"{% if extra_link.external %} target="_blank"{% endif %}>
    <span>
        {% if extra_link.icon %}
        <i class="{{ extra_link.icon }}"></i>
        {% endif %}
        {{ extra_link.title }}
    </span>
    {% if extra_link.external %}
    <i class="fas fa-external-link-alt"></i>
    {% endif %}
</a>
{% endif %}

cri_frontend/templates/cri_frontend/_pagination.html
<nav aria-label="Page navigation">
    <div class="d-flex flex-row justify-content-center">
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page=1">&laquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">&laquo;</a>
            </li>
            {% endif %}
            {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
            <li class="page-item active">
                <a class="page-link">
                    {{ i }}
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
            {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ paginator.num_pages }}">&raquo;</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link">&raquo;</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

cri_frontend/templates/cri_frontend/_user_list_picture_item.html
<div class="card m-1" style="width: min-content;">
    <a class="card-img-top" href="https://photos.cri.epita.fr/{{ user.username }}" target="_blank">
        <img src="https://photos.cri.epita.fr/square/{{ user.username }}" alt="{{ user.username }}" style="height: 275px;" />
    </a>
    <a class="btn btn-link btn-light btn-sm card-body p-3 text-monospace" href="{{ user.get_absolute_url }}">
        {{ user.username }}
    </a>
</div>

cri_frontend/templates/cri_frontend/_user_list_table_item.html
<tr>
    {% if form_id %}
    <td class="align-middle">
        <input form="{{ form_id }}" type="checkbox" name="user_list" value="{{ user.pk }}" checked="checked" autocomplete="off" />
    </td>
    {% endif %}
    <td class="text-monospace align-middle">
        <a class="no-tr-check" href="{{ user.get_absolute_url }}">
            {{ user.username }}
        </a>
    </td>
    <td class="align-middle">{{ user.first_name }}</td>
    <td class="align-middle">{{ user.last_name }}</td>
    <td class="text-monospace align-middle">{{ user.email }}</td>
    <td class="align-middle">{{ user.uid }}</td>
    <td class="align-middle">
        <a href="https://photos.cri.epita.fr/{{ user.username }}" target="_blank">
            <img src="https://photos.cri.epita.fr/square/{{ user.username }}" class="no-tr-check img-thumbnail" alt="{{ user.username }}" style="max-height: 75px;" />
        </a>
    </td>
</tr>

cri_frontend/templates/cri_frontend/not_available.html
{% extends "_centered_form.html" %}

{% block form_icon %}<i class="fas fa-ban"></i>{% endblock %}
{% block form_title %}Not available{% endblock %}

{% block form_content %}
{{ block.super }}
<div class="row">
    <div class="col">
        <div class="alert alert-warning text-center" role="alert">
            <strong>
                <i class="fas fa-ban"></i>
                This page is not yet available, please come back later.
            </strong>
        </div>
    </div>
</div>
{% endblock %}